<?php

namespace Autourdujeu\GameBundle\Repository;

/**
 * GameItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameItemRepository extends \Doctrine\ORM\EntityRepository
{
}
